// İmtihan Hazırlık - Soru Bankası (Seviye 1)
export const IMTIHAN_SORULAR = {
  'SEVİYE 1': {
    'Adab-ı Muaşeret': [
      // Temizlik Adabı
      { id: 'adab_1', konu: 'Temizlik Adabı', soru: 'Temizlik ile iman arasındaki ilişkiyi ifade eden hadis-i şerifi söyler misin?', cevap: '"Temizlik, imandandır."' },
      { id: 'adab_2', konu: 'Temizlik Adabı', soru: 'Müslümanın yüzünde, saçında, tırnağında bulunan kirleri temizlemesi, tırnaklarını kesmesi saçlarını taramasının hükmü nedir?', cevap: 'Sünnettir' },
      // Tuvalet Adabı
      { id: 'adab_3', konu: 'Tuvalet Adabı', soru: 'Tuvalete girilmeden önce ne yapılmalıdır?', cevap: 'Eller yıkanır, çoraplar çıkartılarak, pantalonun paçaları sıvanmalıdır.' },
      { id: 'adab_4', konu: 'Tuvalet Adabı', soru: '"Allah" ismi şerifi ve peygamber isimleri yazılı bir şeyle tuvalete girilebilir mi?', cevap: 'Girilmemeli' },
      { id: 'adab_5', konu: 'Tuvalet Adabı', soru: 'Tuvalete hangi ayakla girilir ve hangi ayakla çıkılır?', cevap: 'Sol ayakla girilir sağ ayakla çıkılır.' },
      { id: 'adab_6', konu: 'Tuvalet Adabı', soru: 'Tuvalet ihtiyacı ayakta giderilir mi?', cevap: 'Hayır' },
      { id: 'adab_7', konu: 'Tuvalet Adabı', soru: 'Tuvalette taharet için hangi el kullanılmalıdır?', cevap: 'Sol el.' },
      { id: 'adab_8', konu: 'Tuvalet Adabı', soru: 'Taharet nasıl yapılır?', cevap: 'Önce tuvalet kağıdı ile kurulanır, sonra su ile temizlenip tekrar kağıtla kurulanır.' },
      { id: 'adab_9', konu: 'Tuvalet Adabı', soru: 'Tuvalete otururken hangi yöne dikkat edilmelidir?', cevap: 'Kıble yönünde olmamaya dikkat edilir.' },
      { id: 'adab_10', konu: 'Tuvalet Adabı', soru: 'Tuvalette neler yapılmamalıdır?', cevap: 'Avret yerlerine ve pisliklere bakılmaz. Tuvalete tükürülmez. Tuvalette bir şey yenilmez ve içilmez, sakız çiğnenmez. Tuvalette konuşulmaz, gazete-kitap okunmaz, telefona bakılmaz. Tuvalette oyalanılmaz.' },
      { id: 'adab_11', konu: 'Tuvalet Adabı', soru: 'Tuvalete girilmeden önce hangi dua okunur?', cevap: 'Eûzü billahi minel hubsi vel habâis' },
      { id: 'adab_12', konu: 'Tuvalet Adabı', soru: 'Tuvaletten çıktıktan sonra hangi dua okunur?', cevap: 'Elhamdülillâhillezi ezhebe annel ezâ ve âfâni min zalik.' },
      // Klozet Kullanımı
      { id: 'adab_13', konu: 'Klozet Kullanımı', soru: 'Klozeti kullanmadan önce ne yapılmalı?', cevap: 'Vücudun temas edeceği yüzeyler necaset kalmayacak şekilde temizlenmelidir.' },
      { id: 'adab_14', konu: 'Klozet Kullanımı', soru: 'Klozet kullanımında sifon ne zaman çekilmelidir?', cevap: 'Klozetin kapağı kapalıyken sifon çekilmelidir.' },
      // Mescid Adabı
      { id: 'adab_15', konu: 'Mescid Adabı', soru: 'Mescide girilmeden önce ne yapılmalıdır?', cevap: 'Kişisel temizliğine dikkat edip abdest almalıdır.' },
      { id: 'adab_16', konu: 'Mescid Adabı', soru: 'Mescide hangi ayakla girilir hangi ayakla çıkılır?', cevap: 'Sağ ayakla girilir, sol ayakla çıkılır.' },
      { id: 'adab_17', konu: 'Mescid Adabı', soru: 'Cemaate hangi safta oturulmaya dikkat edilmelidir?', cevap: 'İlk safta' },
      { id: 'adab_18', konu: 'Mescid Adabı', soru: 'Mescidde sohbet yapılıyorsa nasıl hareket etmelidir?', cevap: 'Sessizce, can kulağı ile dinlenmelidir.' },
      // Dua Adabı
      { id: 'adab_19', konu: 'Dua Adabı', soru: 'Dua nasıl inanılarak edilmelidir?', cevap: 'Dua, samimi bir şekilde kabul olunacağına inanarak kalpten edilmelidir.' },
      { id: 'adab_20', konu: 'Dua Adabı', soru: 'Dua edilirken eller nasıl tutulur?', cevap: 'Göğüs hizasına kaldırılıp birleştirerek dua etmek güzeldir.' },
      { id: 'adab_21', konu: 'Dua Adabı', soru: 'Duanın kabul olmasına vesile olarak neler yapılmalıdır?', cevap: 'Duaya hamd ederek başlayıp Peygamber Efendimize Salevât-ı Şerife ile devam etmek ve duanın sonunda tekrar Salevât-ı Şerife getirmek.' },
      { id: 'adab_22', konu: 'Dua Adabı', soru: 'Dua ederken duaya kimler dahil edilmelidir?', cevap: 'Sadece kendine dua etmemelidir. Anne babaya, sevdiklerine ve diğer bütün Müslümanlara da dua edilmelidir.' },
      { id: 'adab_23', konu: 'Dua Adabı', soru: 'Duaların sonunda "Allah\'ım, kabul et!" manasına gelen ne denir?', cevap: 'Âmin' },
      // Uyku Adabı
      { id: 'adab_24', konu: 'Uyku Adabı', soru: 'Yatmadan önce dikkat edilmesi gerekenler nelerdir?', cevap: 'Temizliğe dikkat edilmeli, eller yıkanıp dişler fırçalanmalıdır. Abdestli bir şekilde yatılmalıdır.' },
      { id: 'adab_25', konu: 'Uyku Adabı', soru: 'Yatmadan önce hangi dua okunur?', cevap: 'Allâhümme bismike emûtü ve ahyâ' },
      { id: 'adab_26', konu: 'Uyku Adabı', soru: 'Hangi tarafa dönerek yatılır?', cevap: 'Sağ tarafa dönerek yatılır.' },
      { id: 'adab_27', konu: 'Uyku Adabı', soru: 'Sağ tarafa dönerek yatmanın hükmü nedir?', cevap: 'Sünnettir' },
      { id: 'adab_28', konu: 'Uyku Adabı', soru: 'Uyanınca okunacak dua nedir?', cevap: 'Elhamdülillâhillezî ahyânâ ba\'de mâ emâtenâ ve ileyhil ba\'sü vennüşûr.' },
      // Giyinme Adabı
      { id: 'adab_29', konu: 'Giyinme Adabı', soru: 'Giyinmekteki öncelikli maksat nedir?', cevap: 'Avret yerlerinin örtülmesi.' },
      { id: 'adab_30', konu: 'Giyinme Adabı', soru: 'Giyinirken ve çıkarırken hangi taraftan başlanmalıdır?', cevap: 'Giyinirken sağ taraftan, çıkarırken sol taraftan başlanmalıdır.' },
      { id: 'adab_31', konu: 'Giyinme Adabı', soru: 'Elbise giyilirken ne söylenir?', cevap: 'Besmele' },
      { id: 'adab_32', konu: 'Giyinme Adabı', soru: 'Çıkarılan elbise nasıl konulur?', cevap: 'Çıkarılan elbiseler katlanılarak konulmalıdır.' },
      { id: 'adab_33', konu: 'Giyinme Adabı', soru: 'Giyilen elbisenin uzunluk ve kısalığı nasıl olmalıdır?', cevap: 'Giyilen elbise ne uzun olup yerde sürünmeli ne de kısa olup topuk gözükmelidir.' },
      // Yemek Adabı
      { id: 'adab_34', konu: 'Yemek Adabı', soru: 'Yemekten önce ve sonra ne yapılır?', cevap: 'Eller yıkanır.' },
      { id: 'adab_35', konu: 'Yemek Adabı', soru: 'Yemeğe başlamadan ne söylenir?', cevap: 'Bismillâhirrahmânirrahîm' },
      { id: 'adab_36', konu: 'Yemek Adabı', soru: 'Yemeğin başında besmeleyi unutanlar hatırladığında ne söylemeli?', cevap: 'Bismillâhi fî evvelihî ve âhirihî' },
      { id: 'adab_37', konu: 'Yemek Adabı', soru: 'Yemeğe tuz ile başlayıp tuz ile bitirmenin hükmü nedir?', cevap: 'Sünnettir' },
      { id: 'adab_38', konu: 'Yemek Adabı', soru: 'Yemek masasında bir büyük varsa ne yapılır?', cevap: 'Yemeğe önce onun başlaması beklenir' },
      { id: 'adab_39', konu: 'Yemek Adabı', soru: 'Yemek ayakta yenir mi?', cevap: 'Yemek oturarak yemeli; ayakta, yürürken, yolda veya sokakta bir şeyler yememelidir.' },
      { id: 'adab_40', konu: 'Yemek Adabı', soru: 'Yemekler hangi sıcaklıkta yenmelidir?', cevap: 'Yemekleri çok sıcak yememeli, soğuması için üflememelidir.' },
      { id: 'adab_41', konu: 'Yemek Adabı', soru: 'Yemekler hangi el ile yenir?', cevap: 'Sağ eliyle kendi önünden yemelidir.' },
      { id: 'adab_42', konu: 'Yemek Adabı', soru: 'Tabağa ne kadar yemek alınır?', cevap: 'Tabağa, yiyebilecek kadar yemek almalı, tabaktaki yemek bitirilmeli ve tabak sünnetlenmelidir.' },
      { id: 'adab_43', konu: 'Yemek Adabı', soru: 'Ağızda lokma varken ne yapılmaz?', cevap: 'Konuşulmaz' },
      { id: 'adab_44', konu: 'Yemek Adabı', soru: 'Yemekten sonra hangi dua yapılır?', cevap: 'Yemek duası' },
      { id: 'adab_45', konu: 'Yemek Adabı', soru: 'Yemek bittikten sonra ağızdaki kalıntıları gidermek için ne yapılır?', cevap: 'Biraz su içilerek ağızdaki ekmek ve yemek kalıntıları giderilmelidir.' },
      { id: 'adab_46', konu: 'Yemek Adabı', soru: 'Yemeği yapana ne denir?', cevap: 'Elinize sağlık!' },
      // Su İçme Adabı
      { id: 'adab_47', konu: 'Su İçme Adabı', soru: 'Su nasıl içilir?', cevap: 'Su ayakta içilmez. Mümkünse kıbleye dönülüp oturarak veya diz çökerek içilir. (Zemzem-i Şerif suyu ayakta içilir)' },
      { id: 'adab_48', konu: 'Su İçme Adabı', soru: 'Suyu içmeden önce ve içtikten sonra ne denir?', cevap: 'İçmeden önce Besmele çekilir, içtikten sonra Elhamdülillah denir.' },
      { id: 'adab_49', konu: 'Su İçme Adabı', soru: 'Su hangi elle tutularak ve kaç yudumda içilir?', cevap: 'Su, sağ elle her yudum arasında nefes alarak ve her seferde besmele ile üç yudumda içilmelidir.' },
      { id: 'adab_50', konu: 'Su İçme Adabı', soru: 'Bir topluluğa su dağıtılırken nelere dikkat edilir?', cevap: 'Su yaşlılardan başlanılarak dağıtılır en son kendisi içer. Sırayla dağıtılacaksa sağdan başlanılır. Suyu dağıtan, sürahiyi sol eliyle, bardağı sağ eliyle tutar.' },
      { id: 'adab_51', konu: 'Su İçme Adabı', soru: 'Zemzem-i Şerif suyu ikram edildiğinde ne yapılmaz?', cevap: 'Geri çevrilmez.' },
      // Konuşma Adabı
      { id: 'adab_52', konu: 'Konuşma Adabı', soru: 'Konuşurken nelere dikkat edilmelidir?', cevap: 'Doğru söz söylenmeli, gereksiz boş sözlerden kaçınılmalıdır. Başkası konuşurken sözü kesilmemelidir.' },
      { id: 'adab_53', konu: 'Konuşma Adabı', soru: 'Toplum içerisinde nasıl konuşulmaz?', cevap: 'Fısıldaşarak' },
      { id: 'adab_54', konu: 'Konuşma Adabı', soru: 'Selamlaşma ile alakalı hadis-i şerif nedir?', cevap: 'Selam, Allâhü Teâlâ\'nın isimlerindendir. Onu aranızda yayınız.' },
      // Selamlaşma Adabı
      { id: 'adab_55', konu: 'Selamlaşma Adabı', soru: 'Karşılaşılan iki Müslümandan biri ne der, diğeri ona nasıl karşılık verir?', cevap: 'Biri "Selamün Aleyküm" diyerek selam verir. Diğer kişi "Ve aleyküm selam" diye karşılık vererek selamı alır.' },
      { id: 'adab_56', konu: 'Selamlaşma Adabı', soru: 'Yürüyen ile oturan arasında kim selam verir?', cevap: 'Yürüyen oturana selam verir.' },
      { id: 'adab_57', konu: 'Selamlaşma Adabı', soru: 'Küçük ile büyük arasında kim selam verir?', cevap: 'Küçük olan büyük olana selam verir.' },
      { id: 'adab_58', konu: 'Selamlaşma Adabı', soru: 'Araçla giden ile yaya arasında kim selam verir?', cevap: 'Araçla giden yaya olarak gidene selam verir.' },
      { id: 'adab_59', konu: 'Selamlaşma Adabı', soru: 'Arkadan gelen ile önde olan arasında kim selam verir?', cevap: 'Arkadan gelen, önde olana selam verir.' },
      { id: 'adab_60', konu: 'Selamlaşma Adabı', soru: 'Az olan ile çok olan arasında kim selam verir?', cevap: 'Az olan çok olana selam verir.' },
      { id: 'adab_61', konu: 'Selamlaşma Adabı', soru: 'Selam vermek ve selamı almanın hükmü nedir?', cevap: 'Selam vermek sünnet, almak farzdır.' },
      { id: 'adab_62', konu: 'Selamlaşma Adabı', soru: 'Topluluk halinde selam nasıl verilir ve alınır?', cevap: 'Topluluk halinde bir kişinin selamı vermesi ve alması yeterlidir.' },
      // Arkadaşlık Adabı
      { id: 'adab_63', konu: 'Arkadaşlık Adabı', soru: 'Arkadaşımızın ihtiyacı anında ne yapmalıyız?', cevap: 'Hemen yardımına koşmalıyız.' },
      { id: 'adab_64', konu: 'Arkadaşlık Adabı', soru: 'Arkadaşımız bize sır vediyse ne yapmalıyız?', cevap: 'Sırrını gizlemeliyiz.' },
      { id: 'adab_65', konu: 'Arkadaşlık Adabı', soru: 'Arkadaşımızın gördüğümüz ayıp ve kusurları için ne yapmalıyız?', cevap: 'Ayıp ve kusurlarını örtmeli, iyilikle nasihat etmeliyiz.' },
      { id: 'adab_66', konu: 'Arkadaşlık Adabı', soru: 'Arkadaşımız bize geldiği zaman nasıl davranmalıyız?', cevap: 'Bize geldiği zaman ayakta karşılamalı, güler yüzle selamını almalı, ona yer vermeli, halini-hatrını sormalıyız.' },
      { id: 'adab_67', konu: 'Arkadaşlık Adabı', soru: 'Nasıl kişilerle arkadaşlık kurmalıyız?', cevap: 'Allahü Teâlâ\'nın emirlerine uyan, cömert, doğru sözlü ve doğru davranışlı kişilerle arkadaşlık kurmalıyız.' },
      // Anne Babaya Hürmet
      { id: 'adab_68', konu: 'Anne Babaya Hürmet', soru: 'Anne babamız konuşurken ne yapmalıyız?', cevap: 'Onlar konuşurken dinlemeli, sözlerini kesmemeliyiz.' },
      { id: 'adab_69', konu: 'Anne Babaya Hürmet', soru: 'Anne babamız muhtaç olduğunda ne yapmalıyız?', cevap: 'Muhtaç olduklarında yedirip giydirmeli, ihtiyaçlarını karşılamalı, hizmetlerinde bulunmalıyız.' },
      { id: 'adab_70', konu: 'Anne Babaya Hürmet', soru: 'Anne babamızın dinimize aykırı olmayan sözleri için ne yapmalıyız?', cevap: 'Dinlemeli, onları incitecek söz ve davranışlardan kaçınmalıyız.' },
      { id: 'adab_71', konu: 'Anne Babaya Hürmet', soru: 'Anne babamıza nasıl hitap etmeliyiz?', cevap: 'Onlara güzel sözlerle hitap etmeli, nazik davranmalıyız.' },
      { id: 'adab_72', konu: 'Anne Babaya Hürmet', soru: 'Anne babamız hayatta iken önemli kararlar alırken ne yapmalıyız?', cevap: 'Anne babamıza danışmalıyız.' },
      { id: 'adab_73', konu: 'Anne Babaya Hürmet', soru: 'Ev işlerinde anne babamıza ne yapmalıyız?', cevap: 'Yardım etmeliyiz.' },
      // Cuma Günü Adapları
      { id: 'adab_74', konu: 'Cuma Günü Adapları', soru: 'Cuma günü hakkındaki hadis-i şerif nedir?', cevap: '"Üzerine güneşin doğduğu en hayırlı gün, Cuma günüdür…"' },
      { id: 'adab_75', konu: 'Cuma Günü Adapları', soru: 'Cuma günü ne yapılmalıdır?', cevap: 'Gusül abdesti alınıp, güzel hafif kokular sürülmeli, tırnak kesilmeli, misvak kullanılmalı, yeni elbiseler giyilmeli, mümkünse beyaz elbiseler tercih edilmeli, sadaka verilmelidir.' },
      { id: 'adab_76', konu: 'Cuma Günü Adapları', soru: 'Cuma Namazına giderken karşılaşılan Müslümanlara ne yapılmalı?', cevap: 'Selam verilmelidir, Cumaları tebrik edilmelidir.' },
      { id: 'adab_77', konu: 'Cuma Günü Adapları', soru: 'Cuma günü manevi olarak neler yapılmalıdır?', cevap: 'Kur\'an-ı Kerim okunmalı ve ibadet edilmelidir. Cuma günü ve geceleri çok salevâ getirilmelidir.' },
      { id: 'adab_78', konu: 'Cuma Günü Adapları', soru: 'Cuma günü geldiğinde sevinen kişiyi müjdeleyen hadis-i şerif nedir?', cevap: '"Cuma günü geldiği için sevinen bir mümine, kıyamette kadar her gün, o kadar sevap verilir ki, adedini Allahü Teâlâ bilir."' },
      // Misafirlik Adabı
      { id: 'adab_79', konu: 'Misafirlik Adabı', soru: 'Misafire ikram ile alakalı hadis-i şerif nedir?', cevap: 'Kim Allah\'a ve ahiret gününe iman ediyorsa, misafirine ikram etsin.' },
      { id: 'adab_80', konu: 'Misafirlik Adabı', soru: 'Ev sahibi misafirler gelmeden önce eve ne yapılmalıdır?', cevap: 'Misafirler gelmeden önce ev temizlenip düzenlenmelidir.' },
      { id: 'adab_81', konu: 'Misafirlik Adabı', soru: 'Ev sahibi misafirleri nasıl karşılamalıdır?', cevap: 'Misafiri güler yüzle kapıda karşılamalı, selamını alarak "Hoş geldiniz!" denilmelidir.' },
      { id: 'adab_82', konu: 'Misafirlik Adabı', soru: 'Misafirler gideceği zaman ev sahibi ne yapmalıdır?', cevap: 'Gidecekleri zaman, kapıya kadar uğurlamak sünnettir.' },
      { id: 'adab_83', konu: 'Misafirlik Adabı', soru: 'Bir yere misafirliğe gidilmeden önce ne yapılır?', cevap: 'Ev sahibine müsait olup olmadığı sorulmalıdır.' },
      { id: 'adab_84', konu: 'Misafirlik Adabı', soru: 'Misafirliğe gidilirken mümkünse ne alınmalıdır?', cevap: 'Ufak bir hediye' },
      { id: 'adab_85', konu: 'Misafirlik Adabı', soru: 'Misafir kapıya en fazla kaç kez vurur ya da zili en fazla kaç kez çalar?', cevap: 'Kapıya en fazla 3 defa vurulmalı veya zile 3 defa basılmalıdır.' },
      { id: 'adab_86', konu: 'Misafirlik Adabı', soru: 'Misafir evdeki eşyaları nasıl kullanır?', cevap: 'İzin alarak kullanır. İzinsiz kullanmaz.' },
      // Seyahat Adabı
      { id: 'adab_87', konu: 'Seyahat Adabı', soru: 'Araca binince ne okunur?', cevap: 'Araç duası' },
      { id: 'adab_88', konu: 'Seyahat Adabı', soru: 'Yolculuğun rahat, kazasız geçmesi için yolculuğa çıkmadan önce ve döndükten sonra ne verilmelidir?', cevap: 'Sadaka' },
      { id: 'adab_89', konu: 'Seyahat Adabı', soru: 'Yolculuktan dönerken mümkünse aileye ne alınmalıdır?', cevap: 'Hediye' },
      { id: 'adab_90', konu: 'Seyahat Adabı', soru: 'Toplu taşımada yaşlılar, hastalar, hamileler araca bindiğinde ne yapılmalıdır?', cevap: 'Yer verilmelidir.' },
      // Telefon ve İnternet Kullanımı
      { id: 'adab_91', konu: 'Telefon ve İnternet Kullanımı', soru: 'İnternet ya da telefon üzerinde bilgi paylaşımı yapılmadan önce neye dikkat edilmelidir?', cevap: 'Bilgilerin doğruluğundan tam olarak emin olmadan paylaşım yapılmamalıdır.' },
      { id: 'adab_92', konu: 'Telefon ve İnternet Kullanımı', soru: 'Online ortamda şahsi bilgiler paylaşılacağı zaman nelere dikkat edilmelidir?', cevap: 'Şahsi bilgiler, başkalarının göreceği yerlerde asla paylaşılmamalıdır.' },
      { id: 'adab_93', konu: 'Telefon ve İnternet Kullanımı', soru: 'Başkalarının özel bilgileri online ortamda paylaşılmadan önce ne yapılmalıdır?', cevap: 'Bilgileri paylaşılacağı kişiden izin alınmalıdır.' },
      { id: 'adab_94', konu: 'Telefon ve İnternet Kullanımı', soru: 'Arama yapıldığında nezaketen en fazla kaç kez çaldırılmalıdır?', cevap: 'Üç kez' },
      { id: 'adab_95', konu: 'Telefon ve İnternet Kullanımı', soru: 'Görüntülü arama yapılmadan önce ne yapılmalıdır?', cevap: 'Karşı taraf önceden bilgilendirilmelidir.' },
      { id: 'adab_96', konu: 'Telefon ve İnternet Kullanımı', soru: 'Yenilen ve içilen şeyler, internet ortamlarında neden paylaşılmamalıdır?', cevap: 'Kul hakkı, güvenlik vb. sebeplerden dolayı' },
      // Bazı Güzel Tavsiyeler
      { id: 'adab_97', konu: 'Bazı Güzel Tavsiyeler', soru: 'Özel konuşmalar, izinsiz dinlenilir mi?', cevap: 'Hayır' },
      { id: 'adab_98', konu: 'Bazı Güzel Tavsiyeler', soru: 'Aile içi konular, başka yerlerde anlatılır mı?', cevap: 'Hayır' },
      { id: 'adab_99', konu: 'Bazı Güzel Tavsiyeler', soru: 'Büyüklerin sözü kesilir mi?', cevap: 'Hayır' },
      { id: 'adab_100', konu: 'Bazı Güzel Tavsiyeler', soru: 'Yeni tanışılan insanlara ve bizden büyüklere nasıl hitap edilir?', cevap: 'Siz diye hitap edilir.' },
      { id: 'adab_101', konu: 'Bazı Güzel Tavsiyeler', soru: 'Konuşan iki kişinin arasına girilmez. Söylenilecek bir şey varsa ne yapılır?', cevap: 'Konuşmanın bitmesi beklenir.' },
      { id: 'adab_102', konu: 'Bazı Güzel Tavsiyeler', soru: 'Yapılan yanlış ve hatalardan dolayı ne yapılır?', cevap: 'Özür dilenir.' },
      // Dua Ezberi
      { id: 'adab_103', konu: 'Dua Ezberi', soru: 'Tuvalete Girerken ve Çıkarken Okunacak Duayı Okur musun?', cevap: 'Girerken: Eûzü billahi minel hubsi vel habâis / Çıkarken: Elhamdülillâhillezi ezhebe annel ezâ ve âfâni min zalik' },
      { id: 'adab_104', konu: 'Dua Ezberi', soru: 'Sabah Namazının Sünneti ile Farzı Arasında Okunacak ve Tesbih Duaları Okur musun?', cevap: '(Ezber sorusu - yüzünden okur)' },
      { id: 'adab_105', konu: 'Dua Ezberi', soru: 'Yatmadan Önce ve Uyandıktan Sonra Okunacak Duaları Okur musun?', cevap: 'Yatmadan: Allâhümme bismike emûtü ve ahyâ / Uyanınca: Elhamdülillâhillezî ahyânâ ba\'de mâ emâtenâ ve ileyhil ba\'sü vennüşûr.' },
      { id: 'adab_106', konu: 'Dua Ezberi', soru: 'Evden Çıkarken ve Araçlara Binerken Okunacak Duaları Okur musun?', cevap: '(Ezber sorusu - yüzünden okur)' },
    ],

    'Ezber': [
      { id: 'ezber_1', konu: 'Sure Ezberi', soru: 'Fil Suresini Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_2', konu: 'Sure Ezberi', soru: 'Kureyş Suresini Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_3', konu: 'Sure Ezberi', soru: 'Maun Suresini Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_4', konu: 'Sure Ezberi', soru: 'Kevser Suresini Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_5', konu: 'Sure Ezberi', soru: 'Kafirun Suresini Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_6', konu: 'Sure Ezberi', soru: 'Nasr Suresini Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_7', konu: 'Sure Ezberi', soru: 'Tebbet Suresini Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_8', konu: 'Sure Ezberi', soru: 'İhlas Suresini Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_9', konu: 'Sure Ezberi', soru: 'Felak Suresini Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_10', konu: 'Sure Ezberi', soru: 'Nas Suresini Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_11', konu: 'Dua Ezberi', soru: 'Yemek Duasını Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_12', konu: 'Özel Ezber', soru: 'Ayet\'ül Kürsi\'yi Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_13', konu: 'Özel Ezber', soru: 'Huvallahüllezi\'yi Okuyunuz', cevap: '(Ezberlenerek okunur)' },
      { id: 'ezber_14', konu: 'Özel Ezber', soru: 'Amenerrasülü\'yü Okuyunuz', cevap: '(Ezberlenerek okunur)' },
    ],

    'İlmihal': [
      // Ef'al-i Mükellefin
      { id: 'ilm_1', konu: "Ef'al-i Mükellefin", soru: "Ef'al-i Mükellefîn nedir?", cevap: "Mükelleflerin, yani İslam dinine göre sorumluluk sahibi olanların yapmaları veya yapmamaları gereken şeylere efali mükellefin denir." },
      { id: 'ilm_2', konu: "Ef'al-i Mükellefin", soru: "Ef'âl-i mükellefîn kaçtır? Açıklayınız.", cevap: "Sekizdir: farz (farz ayn, farz kifaye), vacip, sünnet (sünnet müekkede, sünnet gayrı müekkede), müstehap, mübah, mekruh, müfsid, haram." },
      { id: 'ilm_3', konu: "Ef'al-i Mükellefin", soru: "Farz nedir?", cevap: "Kesin deliller ile sabit olan, Allahü Teala ve Peygamber Efendimizin emrettikleri hükümlerdir." },
      { id: 'ilm_4', konu: "Ef'al-i Mükellefin", soru: "Farz-ı ayn nedir?", cevap: "Her Müslümanın ancak kendisinin yapması ile yerine gelen amellerdir. Beş vakit namaz gibi." },
      { id: 'ilm_5', konu: "Ef'al-i Mükellefin", soru: "Farz-ı kifaye nedir?", cevap: "Bazı Müslümanların yapmaları ile diğer Müslümanlardan sorumluluğu kaldıran farzlardır. Cenaze namazı gibi." },
      { id: 'ilm_6', konu: "Ef'al-i Mükellefin", soru: "Vacip nedir?", cevap: "Farz kadar açık ve kesin olmamakla birlikte Allâhü Teala tarafından yapılması emredilen amellerdir. Kurban kesmek ve vitir namazı gibi." },
      { id: 'ilm_7', konu: "Ef'al-i Mükellefin", soru: "Sünnet nedir?", cevap: "Peygamber Efendimizin mübarek sözü, işledikleri ve başkası yaptığında hoş gördüğü şeylerdir." },
      { id: 'ilm_8', konu: "Ef'al-i Mükellefin", soru: "Sünnet-i müekkede nedir?", cevap: "Peygamber Efendimizin devamlı olarak yapıp, çok az terk ettiği sünnetlerdir. Sabah ve öğle namazının sünnetleri gibi." },
      { id: 'ilm_9', konu: "Ef'al-i Mükellefin", soru: "Sünnet-i gayr-i müekkede nedir?", cevap: "Peygamber Efendimizin bazen yapıp çoğu kere terk ettiği sünnetlerdir. İkindi ve yatsı namazının ilk sünnetleri gibi." },
      { id: 'ilm_10', konu: "Ef'al-i Mükellefin", soru: "Müstehap nedir?", cevap: "Peygamber Efendimizin bazen işlediği şeylerdir. Sadaka vermek" },
      { id: 'ilm_11', konu: "Ef'al-i Mükellefin", soru: "Mübah nedir?", cevap: "Yapılmasında sevap, yapılmamasında günah olmayan şeylerdir. Oturmak, kalkmak gibi." },
      { id: 'ilm_12', konu: "Ef'al-i Mükellefin", soru: "Mekruh nedir?", cevap: "İşlenmesi hoş görülmeyen ve amellerin sevabını azaltan şeylerdir. Namazdayken esnemek gibi." },
      { id: 'ilm_13', konu: "Ef'al-i Mükellefin", soru: "Müfsid nedir?", cevap: "Başlanılan bir ibadeti bozan şeylerdir. Namazdayken gülmek gibi." },
      { id: 'ilm_14', konu: "Ef'al-i Mükellefin", soru: "Haram nedir?", cevap: "Yapılması kesin delille yasaklanan şeylerdir. Hırsızlık yapmak gibi." },
      // İslam'ın Şartları
      { id: 'ilm_15', konu: "İslam'ın Şartları", soru: "İslam'ın şartları kaçtır? Nelerdir?", cevap: "Beştir: 1. Kelime-i şehadet getirmek, 2. Namaz kılmak, 3. Zekat vermek, 4. Ramazanı Şerif orucunu tutmak, 5. Hac etmek." },
      { id: 'ilm_16', konu: "İslam'ın Şartları", soru: "Kelime-i Şehadet ve anlamı nedir?", cevap: "Ben şehadet ederim ki Allah'tan başka ilah yoktur ve ben yine şehadet ederim ki Muhammed aleyhisselam Allah'ın kulu ve rasulüdür." },
      // Namaz
      { id: 'ilm_17', konu: "Namaz", soru: "Namazın farzlarını sayar mısın?", cevap: "Namazın Farzı 12'dir. Altısı Rükün, altısı şarttır. Şartları: Hadastan Taharet, Necasetten Taharet, Sırt-ı Avret, İstikabeli Kıble, Vakit, Niyet. Rükünleri: İftitah Tekbiri, Kıyam, Kıraat, Rüku, Secde, Ka'de-i Ahire." },
      // Abdest
      { id: 'ilm_18', konu: "Abdest", soru: "Abdestin farzı nedir?", cevap: "1. Yüzü yıkamak, 2. Elleri ve kolları dirseklerle birlikte yıkamak, 3. Başın dörtte birini meshetmek, 4. Ayakları, topuklarla beraber bileklere kadar yıkamak" },
      { id: 'ilm_19', konu: "Abdest", soru: "Abdestin sünnetleri nedir? (Beş madde sayınız.)", cevap: "1-Eûzü ve Besmele ile başlamak, 2-Niyet etmek, 3-Önce ellerini bileklerine kadar yıkamak, 4-Ağza ve burna üç kere su vermek, 5-Misvak kullanmak (ve diğerleri)" },
      { id: 'ilm_20', konu: "Abdest", soru: "Abdestin mekruhları nedir? (Beş madde sayınız.)", cevap: "1.Sol el ile ağza su vermek, 2.Sağ el ile sümkürmek, 3.Suyu yüzüne çarpmak, 4.Suyu israf etmek, 5.Üç kere yıkanması gereken uzvu üç defadan az veya fazla yıkamak" },
      { id: 'ilm_21', konu: "Abdest", soru: "Abdesti bozan durumlar nedir? (Beş madde sayınız.)", cevap: "1-Küçük veya büyük tuvaletini yapmak, 2-Önden veya arkadan sıvı çıkması, 3-Vücuttan kan/irin akması, 4-Ağız dolusu kusmak, 5-Delirmek/bayılmak" },
      { id: 'ilm_22', konu: "Abdest", soru: "Kaplama mesh nasıl yapılır?", cevap: "Sağ elin dört parmağı sağ tarafa, sol elin dört parmağı sol tarafa koyularak başın tamamı meshedilir." },
      // Gusül
      { id: 'ilm_23', konu: "Gusül", soru: "Gusül abdesti nedir?", cevap: "Boy abdesti diye de bilinen gusül abdesti; ağız ve burnun içi dahil olmak üzere baştan ayağa bütün vücudu yıkayarak yapılan dini bir temizliktir." },
      { id: 'ilm_24', konu: "Gusül", soru: "Gusül ne zaman gerekir?", cevap: "Gusül eşler arasındaki cinsi yakınlık, ihtilam, hayız ve nifasın bitmesiyle gerekir." },
      { id: 'ilm_25', konu: "Gusül", soru: "Cünüp iken yapılamayacak ibadetler nelerdir?", cevap: "Farz veya nafile herhangi bir namaz kılamaz. Cami-mescit gibi ibadet yapılan yerlere giremez. Tilavet secdesi yapamaz. Kur'an-ı Kerimi eline alamaz ve okuyamaz. Kabe-i Muazzamayı tavaf edemez." },
      { id: 'ilm_26', konu: "Gusül", soru: "Guslün Farzları nedir?", cevap: "1. Ağza dolu dolu su vermek, 2. Burna dolu dolu su vermek, 3. Bütün bedeni kuru yer kalmayacak şekilde yıkamak." },
      { id: 'ilm_27', konu: "Gusül", soru: "Guslün Sünnetleri nedir?", cevap: "1. Niyet etmek, 2. Ön ve arka avret yerlerini yıkamak, 3. Besmele çekmek, 4. Önce başına sonra sağ daha sonra sol omuzuna üçer defa su dökmek ve her defasında vücudu ovmak" },
      // Teyemmüm
      { id: 'ilm_28', konu: "Teyemmüm", soru: "Teyemmüm nedir?", cevap: "Abdest almak veya gusletmek için suyun bulunmadığı ya da kullanılamadığı hallerde niyet ederek elleri temiz toprak ya da toprak cinsinden bir şeye vurup yüz ve kolları meshetmektir." },
      { id: 'ilm_29', konu: "Teyemmüm", soru: "Teyemmümün farzı kaçtır? Sayar mısın?", cevap: "İkidir: 1. Niyet, 2. İki darp (vurmak) ve mesh (elleri toprağa vurup yüzü, tekrar vurduktan sonra kolları meshetmek.)" },
      { id: 'ilm_30', konu: "Teyemmüm", soru: "Teyemmümü bozan durumlar nelerdir?", cevap: "1. Abdesti ve guslü bozan her şey, 2. Hastalık, şiddetli soğuk, tehlike gibi teyemmümü gerektirecek durumların ortadan kalkması, 3. Su bulunması" },
      // Mestler Üzerine Mesh
      { id: 'ilm_31', konu: "Mestler Üzerine Mesh", soru: "Mest üzerine mesh yapılabilmesi için ne gereklidir?", cevap: "1. Mestler abdestli iken giyilmiş olmalı, 2. Mestler topuklarla birlikte ayakları örtmeli, 3. Mestler bağsız olarak ayakta durabilecek şekilde kalın olmalı" },
      { id: 'ilm_32', konu: "Mestler Üzerine Mesh", soru: "Meshin miktarı nedir?", cevap: "Mestin ön kısmından üç serçe parmağı kadar yeri ıslatarak meshetmek farzdır." },
      { id: 'ilm_33', konu: "Mestler Üzerine Mesh", soru: "Mest üzerine meshin bozulduğu durumlar nelerdir?", cevap: "1. Abdesti ve gusül abdestini bozan herşey meshide bozar, 2. Mestin ayaktan çıkması, 3. Mestler ayaktayken ayaklardan birinin çoğu kısmının ıslanması, 4. Mesh süresinin bitmesi" },
      { id: 'ilm_34', konu: "Mestler Üzerine Mesh", soru: "Meshin süresi nedir?", cevap: "Abdestli olarak mest giyildikten sonra abdestin bozukduğu ilk namaz vaktinde mesh süresi başlar. Bundan sonra bir gün bir gece (24 saat) boyunca mest üzerine mesh yapılır. Seferi olanlar için bu süre üç gün üç gecedir (72 saat)." },
      // Necasetten Taharet
      { id: 'ilm_35', konu: "Necasetten Taharet", soru: "Necaset kapsamına giren şeyler nelerdir?", cevap: "İnsanın ön ve arkadan çıkan pisliği; eti yenmeyen hayvanların sidiği, dışkısı ve salyası; tavuk, kaz ve ördeğin dışkısı; kan, irin, meni, mezi, vedi; ağız dolusu gelen kusuntu; haram olan bütün içkiler." },
      { id: 'ilm_36', konu: "Necasetten Taharet", soru: "İstincâ nedir?", cevap: "Bir kimsenin büyük veya küçük tuvaletini yaptıktan sonra pisliğin çıktığı avret yerini temizlemesidir." },
      { id: 'ilm_37', konu: "Necasetten Taharet", soru: "İstibrâ nedir?", cevap: "Erkeklerin idrar yaptıktan sonra erkeklik uzvundaki akıntıyı tamamen kesmesidir." },
      // Setr-i Avret
      { id: 'ilm_38', konu: "Setr-i Avret", soru: "Erkeklerin avret yerleri neresidir?", cevap: "Göbeğin altı ile diz kapaklarının altı arasında kalan bölgedir." },
      { id: 'ilm_39', konu: "Setr-i Avret", soru: "Kadınların avret yerleri neresidir?", cevap: "Bileklerine kadar elleri, topuklarına kadar ayakları ve yüzleri hariç bütün vücutları avret mahallidir." },
      // Vakit
      { id: 'ilm_40', konu: "Vakit", soru: "Kerahet vakitleri nelerdir?", cevap: "Güneş doğduktan sonra ~40-50 dk, Öğle namazından önceki ~20 dk, Güneş batarken yani akşam namazından önceki 45 dakika içinde." },
      { id: 'ilm_41', konu: "Vakit", soru: "Kerahet vakitlerinde neler yapılmaz?", cevap: "Kazaya kalmış farz namazlar, vacip namazlar, kerahat vaktinden önce hazırlanmış cenazenin namazı kılınmaz. Tilavet secdesi yapılmaz. Bu üç vakitte nafile namaz kılınmaz." },
      // Namaz Unsurları
      { id: 'ilm_42', konu: "Namaz Unsurları", soru: "İftidah tekbiri nedir?", cevap: "Namaza, 'Allah en büyüktür' manasına gelen 'Allahü Ekber' diyerek başlamaktır. Tekbire, eller yanda iken başlanıp tekbir kulaklarda bitirilir." },
      { id: 'ilm_43', konu: "Namaz Unsurları", soru: "Kıyam nedir?", cevap: "Kıyam ayakta durmaktır ve namaz için şarttır. Ayakta durmaya imkanı olan kişinin oturarak namaz kılması caiz değildir." },
      { id: 'ilm_44', konu: "Namaz Unsurları", soru: "Kıraat nedir ve farz olan kıraat miktarı nedir?", cevap: "Kıraat, namaz kılanın Kur'an-ı Kerim'den birkaç ayet veya bir sure okumasıdır. Farz olan kıraat miktarı, üç kısa ayet veya bu miktarda uzun bir ayet okumaktır." },
      { id: 'ilm_45', konu: "Namaz Unsurları", soru: "Rüku nedir?", cevap: "Ruku, kıyamdan sonra, baş ile sırt düz olacak şekilde elleri dize koyarak Allah'ın huzurunda eğilmektir." },
      { id: 'ilm_46', konu: "Namaz Unsurları", soru: "Secde nedir?", cevap: "Secde; alnı, burnu, iki ayağın parmak uçlarını, iki el ile iki dizi yere koyarak Allah'ın huzurunda yere kapanmaktır." },
      { id: 'ilm_47', konu: "Namaz Unsurları", soru: "Ka'de-i ahîre nedir?", cevap: "Son oturuş demektir. Namazın sonundaki oturuşta Ettehıyyatü duasını okuyacak kadar oturup beklemektir." },
      // Sehiv Secdesi
      { id: 'ilm_48', konu: "Sehiv Secdesi", soru: "Sehiv secdesi nedir?", cevap: "Namazda unutarak ya da bilmeden yapılan bir eksiklik veya fazlalıktan meydana gelen hatayı düzeltmek için yapılması vacip olan bir secdedir." },
      { id: 'ilm_49', konu: "Sehiv Secdesi", soru: "Sehiv secdesi gereken durumlar nelerdir?", cevap: "Namaz içinde farzın sehven geciktirilmesi, vacibin ise sehven terk edilmesi veya geciktirilmesinde gerekir. Mesela sureleri sessiz okuyacağı yerde sesli okuduğunda, vitir namazında kunut dualarını terk ettiğinde." },
    ],

    'Kıraat': [
      { id: 'kiraat_1', konu: 'Yüzüne Okuma', soru: 'Elif Lam Mim (Bakara Suresi 1. Sahife) yüzünden okuyunuz', cevap: '(Yüzünden okunur)' },
      { id: 'kiraat_2', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 2. Sahife yüzünden okuyunuz', cevap: '(Yüzünden okunur)' },
      { id: 'kiraat_3', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 3. Sahife yüzünden okuyunuz', cevap: '(Yüzünden okunur)' },
      { id: 'kiraat_4', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 4. Sahife yüzünden okuyunuz', cevap: '(Yüzünden okunur)' },
      { id: 'kiraat_5', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 5. Sahife yüzünden okuyunuz', cevap: '(Yüzünden okunur)' },
      { id: 'kiraat_6', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 6. Sahife yüzünden okuyunuz', cevap: '(Yüzünden okunur)' },
    ],

    'Siyer-i Nebi': [
      { id: 'siyer_1', konu: 'İlk Vahiy', soru: 'Peygamber Efendimize ilk vahiy kaç yaşında, ne zaman ve nerede gelmiştir?', cevap: 'Kırk yaşında, Ramazan-ı Şerif ayının on yedisi, Pazartesi günü, Hira mağarasında' },
      { id: 'siyer_2', konu: 'İlk Vahiy', soru: 'Peygamber Efendimize ilk gelen vahiy nedir?', cevap: '"Oku! Her şeyi yaratan Rabbinin ismiyle. O, insanı pıhtılaşmış kandan yarattı. Oku ki, senin Rabbin kalemle yazı yazmayı öğreten, insana bilmediğini öğreten, bol kerem ve ihsan sahibidir." (Alak suresi 1-5)' },
      { id: 'siyer_3', konu: 'Hazreti Hatice', soru: 'Peygamber Efendimiz vahiy geldiğini ve peygamberlik vazifesini ilk kime anlatmış ve ilk kim iman etmiştir?', cevap: 'Hz. Hatice Validemiz' },
      { id: 'siyer_4', konu: 'Vahyin Kesilmesi', soru: 'İlk vahiyden bir müddet sonra Cebrail (a.s.) vahiy getirmez olmuştu. Bu durum ne kadar sürdü?', cevap: 'Üç sene kadar sürdü.' },
      { id: 'siyer_5', konu: 'Vahyin Kesilmesi', soru: 'Vahyin kesilmesinin ardından Peygamberimiz gökyüzünden Cebrail\'i görünce "Beni örtün, beni örtün!" dedi. Bunun üzerine hangi ayetler indi?', cevap: '"Ey örtüye bürünen Peygamber! Kalk da sana inanmayanları azapla korkut. Rabbinin büyüklüğünden bahset. Elbiseni temiz tut." (Müddessir Suresi 1-4)' },
      { id: 'siyer_6', konu: 'İlk Müslümanlar', soru: 'Peygamber Efendimizin arkasında ilk namaz kılan kişi kimdir?', cevap: 'Hazreti Hatice Validemiz' },
      { id: 'siyer_7', konu: 'İlk Müslümanlar', soru: 'Peygamber Efendimize iman eden ilk üç kişi kimdir?', cevap: 'Hz. Hatice (r.a.), Hz. Ali (r.a.), Hz. Ebu Bekir (r.a.)' },
      { id: 'siyer_8', konu: 'İlk Müslümanlar', soru: 'İlk üç senede Peygamberimiz İslamiyet\'i nasıl anlattı ve yaklaşık kaç kişi Müslüman oldu?', cevap: 'Peygamberimiz gizli gizli İslamiyet\'i anlattı. Otuzu aşkın kişi Müslüman olmuştu.' },
      { id: 'siyer_9', konu: 'Davet', soru: 'Hz. Ebu Bekir (r.a.) müslüman olduktan sonra Peygamber Efendimiz kimleri İslamiyet\'e davet etmiştir?', cevap: 'Yakın akrabalarını İslamiyete davet etmeye başlamıştır.' },
      { id: 'siyer_10', konu: 'Açık Davet', soru: 'İlk vahiyden üç sene sonra davetler nasıl olmuştur?', cevap: 'Açıktan İslamiyete davet başlamıştır.' },
      { id: 'siyer_11', konu: 'Erkam\'ın Evi', soru: 'Peygamberimiz Mekke\'ye gelenlere daha kolay ulaşabilmek için hangi sahabenin evine taşınmıştır?', cevap: 'Erkam (r.a.)\'ın evine taşındı.' },
      { id: 'siyer_12', konu: 'Erkam\'ın Evi', soru: 'Peygamber Efendimiz ne zamana kadar Erkam (r.a.)\'ın evinde kalmıştır?', cevap: 'Hz. Ömer (r.a.) müslüman oluncaya kadar.' },
      { id: 'siyer_13', konu: 'Peygamberin Kararlılığı', soru: 'Müşrikler para, mal-mülk, şan ve şöhret vaad ettiğinde Peygamberimiz ne buyurmuştur?', cevap: '"Güneşi sağ elime, ayı sol elime verseler ben vazgeçmem." diye buyurmuştur.' },
      { id: 'siyer_14', konu: 'İlk Hicret', soru: 'Müslümanların ilk hicret ettikleri yer neresidir?', cevap: 'Habeşistan' },
      { id: 'siyer_15', konu: 'Hz. Ömer\'in Müslümanlığı', soru: 'Hz. Ömer (r.a.) nasıl müslüman olmuştur?', cevap: 'Peygamber Efendimizi öldürmek için giderken kardeşinin evinde duyduğu Kur\'an-ı Kerim ayetlerinden sonra Erkam (r.a.)\'ın evine giderek Peygamber Efendimizin önünde iman etmiştir.' },
      { id: 'siyer_16', konu: 'Hz. Ömer\'in Müslümanlığı', soru: 'Hz. Ömer (r.a.)\'ın iman etmesiyle beraber müslümanlar nasıl ibadet etmeye başlamıştır?', cevap: 'Açıkça ibadet etmeye başlamışlardır.' },
      { id: 'siyer_17', konu: 'Habeşistan\'a İkinci Hicret', soru: 'Habeşistan\'a hicret eden müslümanları iyi karşılayan hükümdarın ismi nedir?', cevap: 'Necaşi' },
      { id: 'siyer_18', konu: 'Mucize', soru: 'Mucize ne demektir?', cevap: 'Peygamberlerin en büyük alametleri, mucizeleridir. Mucize, harikulade (olağanüstü) hadiselere denir.' },
      { id: 'siyer_19', konu: 'Şakkûl-Kamer', soru: 'Müşrikler ayı ikiye ayırmasını istediklerinde ne oldu?', cevap: 'Peygamberimiz dua ettiğinde ayın bir parçası Ebu Kubeys dağına, bir parçası da Kuaykıan Dağı\'nın üzerine doğru ayrıldı. Bu hadiseye Şakkûl-Kamer denir.' },
      { id: 'siyer_20', konu: 'Hüzün Senesi', soru: 'Peygamber Efendimizin amcası Ebu Talib ve hanımı Hz. Hatice Validemiz\'in vefat ettikleri seneye ne denmiştir?', cevap: 'Hüzün Senesi' },
      { id: 'siyer_21', konu: 'Taif Yolculuğu', soru: 'Peygamber Efendimiz Taif\'e gittiğinde Taifliler ne yapmıştır?', cevap: 'Peygamberimizle alay edip Peygamberimizi taş yağmuruna tutmuşlardır.' },
      { id: 'siyer_22', konu: 'Taif Yolculuğu', soru: 'Dağlar meleği "Şu iki dağı Taif halkının üzerine kapayayım mı?" dediğinde Peygamberimiz nasıl cevap vermiştir?', cevap: '"Hayır, ben onların yok olup gitmesini istemem. Onlar şimdi ne yaptıklarını bilmiyorlar. Umulur ki bu insanların içinden iman eden nesiller çıkar."' },
      { id: 'siyer_23', konu: 'Miraç Mucizesi', soru: 'Peygamberimizin Mirac\'a çıktığı gece bindiği bineğin ismi nedir?', cevap: 'Burak' },
      { id: 'siyer_24', konu: 'Miraç Mucizesi', soru: 'Peygamberimizin Mekke\'den Kudüs\'e ve göklere çıkması mucizelerine ne denir?', cevap: 'İsra ve Miraç mucizeleri denir.' },
      { id: 'siyer_25', konu: 'Hz. Ebu Bekir\'in Lakabı', soru: 'Miraç hadisesinde Hz. Ebu Bekir "O söylüyorsa doğrudur" demesi üzerine Peygamberimiz ona ne ad vermiştir?', cevap: 'Sıddîk adını vermiştir.' },
      { id: 'siyer_26', konu: 'Akabe Biatları', soru: 'Medine\'den gelen Müslümanların Peygamberimiz ile Akabe\'de yaptığı ilk buluşma ve sözleşmeye ne denir?', cevap: 'Birinci Akabe Biatı' },
      { id: 'siyer_27', konu: 'Akabe Biatları', soru: 'Birinci Akabe Biatında Müslüman olan Medine\'lilerin yanında İslam dinini anlatması için Peygamberimiz kimi göndermiştir?', cevap: 'Musab bin Umeyr (r.a.)' },
      { id: 'siyer_28', konu: 'Akabe Biatları', soru: 'Medineden 73 erkek 2 kadın olmak üzere 75 kişinin Peygamberimizi Medine\'ye davet ettiği hadiseye ne denir?', cevap: 'İkinci Akabe Biatı' },
      { id: 'siyer_29', konu: 'Hicret', soru: 'Peygamber Efendimiz kiminle beraber hicret etmiştir?', cevap: 'Hz. Ebu Bekir (r.a.)' },
      { id: 'siyer_30', konu: 'Hicret', soru: 'Peygamber Efendimiz hicret edeceği gece Peygamberimizin yatağına yatan sahabe kimdir?', cevap: 'Hz. Ali (r.a.)' },
      { id: 'siyer_31', konu: 'Hicret', soru: 'Peygamber Efendimiz hicret edeceği gece etrafı müşriklerle sarılı olan evinden çıkarken hangi sureyi okumuştur?', cevap: 'Yasin Suresi' },
      { id: 'siyer_32', konu: 'Sevr Mağarası', soru: 'Peygamber Efendimiz ile Hz. Ebu Bekir (r.a.) Medine\'ye hicret ederlerken gece konaklamak için hangi mağarada kaldılar?', cevap: 'Sevr Mağarası' },
      { id: 'siyer_33', konu: 'Sevr Mağarası', soru: 'Sevr Mağarasının önüne gelen müşrikler ne ile karşılaştılar?', cevap: 'Mağaranın ağzına iki yaban güvercini yuva yapmıştı. Bir örümcek de mağaranın girişine kocaman bir ağ örmüştü.' },
      { id: 'siyer_34', konu: 'Sevr Mağarası', soru: 'Peygamber Efendimiz ve Hz. Ebu Bekir (r.a.) Sevr Mağarasında kaç gün beklemişlerdir?', cevap: 'Üç gün beklemişler dördüncü gün yola çıkmışlardır.' },
      { id: 'siyer_35', konu: 'Medine Hayatı', soru: 'Muhacir kime denir?', cevap: 'Mallarını, mülklerini bırakarak sırf Allah\'ın rızasını kazanmak için Mekke\'den Medine\'ye göç eden Müslümanlara Muhacir denir.' },
      { id: 'siyer_36', konu: 'Medine Hayatı', soru: 'Ensar kime denir?', cevap: 'Mekke\'den gelen Müslüman kardeşlerine kucak açan, onları evlerinde misafir eden ve her türlü yardımda bulunan Medineli Müslümanlara da Ensar denir.' },
      { id: 'siyer_37', konu: 'Mescid-i Nebevi', soru: 'Peygamber Efendimiz Medine\'ye geldiğinde devesinin ilk durduğu arsaya yaptırılan mescidin adı nedir?', cevap: 'Mescid-i Nebevi' },
      { id: 'siyer_38', konu: 'İlk Müezzin', soru: 'Peygamber Efendimiz ezan okumak için kimi vazifelendirmiştir?', cevap: 'Hz. Bilal-i Habeşi (r.a.)' },
      { id: 'siyer_39', konu: 'Ramazan', soru: 'Oruç ne zaman farz kılınmıştır?', cevap: 'Hicretten on sekiz ay sonra Şaban ayında.' },
      { id: 'siyer_40', konu: 'Bedir Savaşı', soru: 'Peygamber Efendimiz Bedir\'e doğru kaç kişi ile hareket etmiştir?', cevap: 'Üç yüz on üç (313) kişi ile.' },
      { id: 'siyer_41', konu: 'Bedir Savaşı', soru: 'Bedir savaşını kim kazanmıştır?', cevap: 'Müslümanlar' },
      { id: 'siyer_42', konu: 'Bedir Savaşı', soru: 'Esir düşen müşriklerden fidye ödeyemeyenler için Peygamberimiz ne buyurmuşlardır?', cevap: '"On kişiye okuma yazma öğreten serbest bırakılacak." diye ilan etmişlerdir.' },
      { id: 'siyer_43', konu: 'Uhud Savaşı', soru: 'Bedir Savaşını kaybeden müşrikler yeniden savaşarak Müslümanların üzerine gittiler. Bu savaşın adı nedir?', cevap: 'Uhud Savaşı' },
      { id: 'siyer_44', konu: 'Uhud Savaşı', soru: 'Uhud Savaşı hangi tarihte meydana gelmiştir?', cevap: '625 yılında' },
      { id: 'siyer_45', konu: 'Uhud Savaşı', soru: 'Uhud Savaşında okçuların tepesindeki okçular yerlerini neden terk etti ve sonrasında ne oldu?', cevap: 'Müşrik ordusunun dağıldığını görünce yerlerini terk edip düşmanın peşine düştüler. Fırsat kollayan müşrik atlıları Müslüman ordusunu arkadan sardı ve Müslümanlar düşman ordularının ortasında kaldı.' },
      { id: 'siyer_46', konu: 'Uhud Savaşı', soru: 'Uhud Savaşında Ebu Sufya\'nın eşi Hind, Vahşi isimli köleyi tutarak kimin şehit olmasına sebep olmuştur?', cevap: 'Hz. Hamza (r.a.)' },
      { id: 'siyer_47', konu: 'Hendek Savaşı', soru: 'Uhud Savaşından sonra Yahudilerin Mekkeli müşrikleri kışkırtması üzerine Peygamberimiz ashabı ile beraber ne yapma kararı almışlardır?', cevap: 'Hendek kazma kararı almışlardır.' },
      { id: 'siyer_48', konu: 'Hendek Savaşı', soru: 'Hendek ne kadar sürede kazılmıştır?', cevap: 'İki hafta gibi kısa bir sürede.' },
      { id: 'siyer_49', konu: 'Hendek Savaşı', soru: 'Hendek Savaşını hangi taraf kazanmıştır ve nasıl kazanılmıştır?', cevap: 'Müslümanlar kazanmıştır. Gece vakti çıkan bir fırtına ile tüm müşrikler geri çekilmek zorunda kalmışlardır.' },
      { id: 'siyer_50', konu: 'Hudeybiye Antlaşması', soru: 'Hudeybiye Antlaşmasının maddeleri nelerdir?', cevap: 'Müslümanlar Kâbe\'yi bir yıl sonra ziyaret edecekler ve Mekke\'de üç gün kalacaklar. İki taraf on yıl süreyle savaşmayacak.' },
      { id: 'siyer_51', konu: 'Hudeybiye Antlaşması', soru: 'Hudeybiye Antlaşmasının önemi nedir?', cevap: 'Mekkeliler Müslümanları ve İslam devletinin varlığını resmen kabul ettiklerini göstermektedir.' },
      { id: 'siyer_52', konu: 'Davet Mektupları', soru: 'Habeşistan kralı Necaşi, Peygamber Efendimizin davet mektubunu alınca ne yapmıştır?', cevap: 'Müslüman olmuştur.' },
      { id: 'siyer_53', konu: 'Mekke\'nin Fethi', soru: 'Mekke\'nin Fethinde Mekkeli müşriklere nasıl muamele edilmiştir?', cevap: 'Müşrikler, isterlerse Mekke\'de kalabilecekler, isterlerse gitmek istedikleri yere serbestçe gidebileceklerdi.' },
      { id: 'siyer_54', konu: 'Veda Haccı', soru: 'Peygamber Efendimizin yaptığı son Hacca ne isim verilmiştir?', cevap: 'Veda Haccı' },
      { id: 'siyer_55', konu: 'Veda Hutbesi', soru: 'Peygamber Efendimizin Veda Haccından sonra yüz binlerce Ashabına yapmış olduğu konuşmaya ne isim verilir?', cevap: 'Veda Hutbesi' },
      { id: 'siyer_56', konu: 'Vefat', soru: 'Peygamber Efendimiz ne zaman vefat etmiştir?', cevap: '12 Rebiülevvel Pazartesi 632 yılında.' },
    ],
  },

  'SEVİYE 2': {
    'Ezber': [
      { id: 's2_ezber_1', konu: 'Sure Ezberi', soru: 'Beyyine Suresini Okuyunuz', cevap: 'Hocana okuyarak göster' },
      { id: 's2_ezber_2', konu: 'Sure Ezberi', soru: 'Zilzal Suresini Okuyunuz', cevap: 'Hocana okuyarak göster' },
      { id: 's2_ezber_3', konu: 'Sure Ezberi', soru: 'Adiyat Suresini Okuyunuz', cevap: 'Hocana okuyarak göster' },
      { id: 's2_ezber_4', konu: 'Sure Ezberi', soru: 'Karia Suresini Okuyunuz', cevap: 'Hocana okuyarak göster' },
      { id: 's2_ezber_5', konu: 'Sure Ezberi', soru: 'Tekasür Suresini Okuyunuz', cevap: 'Hocana okuyarak göster' },
      { id: 's2_ezber_6', konu: 'Sure Ezberi', soru: 'Asr Suresini Okuyunuz', cevap: 'Hocana okuyarak göster' },
      { id: 's2_ezber_7', konu: 'Sure Ezberi', soru: 'Hümeze Suresini Okuyunuz', cevap: 'Hocana okuyarak göster' },
    ],

    'Kıraat': [
      { id: 's2_kiraat_1', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 11. Sahife', cevap: 'Hocana yüzüne okuyarak göster' },
      { id: 's2_kiraat_2', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 12. Sahife', cevap: 'Hocana yüzüne okuyarak göster' },
      { id: 's2_kiraat_3', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 13. Sahife', cevap: 'Hocana yüzüne okuyarak göster' },
      { id: 's2_kiraat_4', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 14. Sahife', cevap: 'Hocana yüzüne okuyarak göster' },
      { id: 's2_kiraat_5', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 15. Sahife', cevap: 'Hocana yüzüne okuyarak göster' },
      { id: 's2_kiraat_6', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 16. Sahife', cevap: 'Hocana yüzüne okuyarak göster' },
      { id: 's2_kiraat_7', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 17. Sahife', cevap: 'Hocana yüzüne okuyarak göster' },
      { id: 's2_kiraat_8', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 18. Sahife', cevap: 'Hocana yüzüne okuyarak göster' },
      { id: 's2_kiraat_9', konu: 'Yüzüne Okuma', soru: 'Bakara Suresi 19. Sahife', cevap: 'Hocana yüzüne okuyarak göster' },
    ],

    'İlmihal': [
      { id: 's2_ilm_1', konu: 'Meleklere İman', soru: 'Melek nedir?', cevap: 'Allahü Teala\'nın nurdan yarattığı ve istedikleri şekle girebilen daima ibadet eden günahsız varlıklardır.' },
      { id: 's2_ilm_2', konu: 'Meleklere İman', soru: 'Meleklerin özelliklerini sayar mısın? (Beş madde sayınız.)', cevap: '1. Gözle görülemezler. 2. Cinsiyetleri yoktur, evlenmezler. 3. Yorulmak bilmezler. 4. Yeme, içme, uyuma ihtiyaçları yoktur. 5. Hiç günah işlemezler.' },
      { id: 's2_ilm_3', konu: 'Dört Büyük Melek', soru: 'Dört büyük meleği sayıp görevlerini söyler misin?', cevap: 'Cebrail: Allah ile peygamberler arasında vasıta. Mikail: Rüzgar, yağış, bitkileri yönetir. İsrafil: Sur üfler, kıyameti gerçekleştirir. Azrail: Ruhları alır.' },
      { id: 's2_ilm_4', konu: 'Dört Büyük Melek', soru: 'Her insanda vazifeli kaç melek vardır?', cevap: '384 vazifeli melek vardır.' },
      { id: 's2_ilm_5', konu: 'Dört Büyük Melek', soru: 'Hafaza Meleklerinin görevi nedir?', cevap: 'İnsanlarda bulunan ve onları koruyan meleklerdir.' },
      { id: 's2_ilm_6', konu: 'Dört Büyük Melek', soru: 'Kirâmen Kâtibîn Meleklerinin görevi nedir?', cevap: 'İnsanın sağında ve solunda bulunan bu melekler iyi ve kötü amelleri yazmakla görevlidir.' },
      { id: 's2_ilm_7', konu: 'Dört Büyük Melek', soru: 'Sual Meleklerinin görevi nedir?', cevap: 'Münker ile Nekir isimli meleklerdir. Vefat eden kimseye "Rabbin kim? Dinin ne? Kitabın ne? Peygamberin kimdir?" sorularını sormakla görevlidir.' },
      { id: 's2_ilm_8', konu: 'Suhuf ve Kitaplar', soru: 'Peygamberlere vahiy olarak gönderilen kitap ve suhufun adedi kaçtır?', cevap: '104 suhuftur.' },
      { id: 's2_ilm_9', konu: 'Suhuf ve Kitaplar', soru: 'Suhuflar kime ve kaç adet gönderilmiştir?', cevap: '10 suhuf Hz. Adem\'e, 50 suhuf Hz. Şit\'e, 30 suhuf Hz. İdris\'e, 10 suhuf Hz. İbrahim\'e.' },
      { id: 's2_ilm_10', konu: 'Suhuf ve Kitaplar', soru: 'Kur\'an-ı Kerim\'in gelmesi ile hangi kitapların hükmü kalkmıştır?', cevap: 'Tevrat, Zebur ve İncil\'in hükmü kalkmıştır.' },
      { id: 's2_ilm_11', konu: 'Suhuf ve Kitaplar', soru: 'Gönderilen kitapların isimleri nedir? Hangi peygamberlere gönderilmiştir?', cevap: 'Tevrat Hz. Musa\'ya, Zebur Hz. Davud\'a, İncil Hz. İsa\'ya, Kur\'an-ı Kerim Hz. Muhammed Mustafa\'ya (s.a.v.).' },
      { id: 's2_ilm_12', konu: 'Suhuf ve Kitaplar', soru: 'Kur\'an-ı Kerim\'in özellikleri nelerdir?', cevap: '114 sure 6666 ayettir. Dünyadaki tüm Kur\'an-ı Kerimler aynıdır. Peygamberimizin en büyük mucizesidir. Ebediyen Allah\'ın korumasında olup değişmez.' },
      { id: 's2_ilm_13', konu: 'Tilavet Secdesi', soru: 'Kur\'an-ı Kerim\'de kaç yerde secde ayeti vardır? Yapılması ne zaman vacip olur?', cevap: '14 yerdedir. Bu ayetleri duyduğumuzda veya okuduğumuzda secde etmemiz vaciptir.' },
      { id: 's2_ilm_14', konu: 'Tilavet Secdesi', soru: 'Tilavet secdesi nasıl yapılır?', cevap: 'Abdestli şekilde kıbleye dönülür, niyet edilir, tekbir alınarak secdeye varılır, üç defa "Sübhane Rabbiyela\'a" denir, tekbir ile ayağa kalkılır.' },
      { id: 's2_ilm_15', konu: 'Peygamberlere İman', soru: 'Peygamber kime denir?', cevap: 'Allahü Teala\'nın dinini, emirlerini, yasaklarını kullarına bildirmek için insanlar arasından seçip gönderdiği mübarek zatlardır.' },
      { id: 's2_ilm_16', konu: 'Peygamberlerin Sıfatları', soru: 'Peygamberler hakkında bilinmesi gereken sıfatlar kaç tanedir? Açıklayınız.', cevap: '5 sıfatı vardır: 1. Sıdk (doğruluk) 2. Emanet (güvenilirlik) 3. Tebliğ (duyurma) 4. Fetanet (zeka) 5. İsmet (masumluk).' },
      { id: 's2_ilm_17', konu: 'Peygamberlerin Sıfatları', soru: 'Peygamberimizin diğer peygamberlerden ayrı olarak kaç vasfı vardır? Açıklayınız.', cevap: '5 vasfı: 1. Bütün peygamberlerden üstün. 2. İns ve cin\'e peygamber. 3. Hatemül Enbiya (son peygamber). 4. Alemlere rahmet. 5. Hükümleri kıyamete kadar devam eder.' },
      { id: 's2_ilm_18', konu: 'Peygamberlerin Sıfatları', soru: 'Kur\'an-ı Kerim\'de ismi geçen peygamberleri sayar mısın?', cevap: 'Adem, İdris, Nuh, Hûd, Salih, İbrahim, Lut, İsmail, İshak, Yakup, Yusuf, Eyüp, Şuayb, Musa, Harun, Davud, Süleyman, Yunus, İlyas, Elyasa, Zülkifl, Zekeriya, Yahya, İsa, Üzeyir, Lokman, Zülkarneyn ve Hz. Muhammed (s.a.v.).' },
      { id: 's2_ilm_19', konu: 'Kader ve Kaza', soru: 'İrade-i cüz\'iyye nedir?', cevap: 'İnsanın Allahü Teala\'nın kendisine verdiği sınırlı bir yetki ve tercihi kullanmasıdır.' },
      { id: 's2_ilm_20', konu: 'Kader ve Kaza', soru: 'Kader nedir?', cevap: 'Ezelden ebede kadar meydana gelecek bütün olayları, Cenab-ı Hakk\'ın ilahi bir programla önceden belirlemesidir.' },
      { id: 's2_ilm_21', konu: 'Kader ve Kaza', soru: 'Kaza nedir?', cevap: 'Allahü Teala\'nın ezelde belirlediği olayların, zamanı gelince gerçekleşmesidir.' },
      { id: 's2_ilm_22', konu: 'Kader ve Kaza', soru: 'Rızık nedir?', cevap: 'Allahü Teala\'nın canlılara gıdalanmaları için verdiği ve onların yediği şeylerdir.' },
      { id: 's2_ilm_23', konu: 'Kader ve Kaza', soru: 'Tevekkül nedir?', cevap: 'Maddi ve manevi sebeplerin hepsini yerine getirdikten sonra neticesini Allah\'tan beklemektir.' },
      { id: 's2_ilm_24', konu: 'İmanın Şartları ve Kaleleri', soru: 'İmanın devamının şartları nedir?', cevap: '1. Gaybe inanmak 2. Helalin helal olduğuna inanmak 3. Haramın haram olduğuna inanmak 4. Daima Allahtan korkmak 5. Mukaddesata hürmet 6. Allahın rahmetinden ümit kesmemek 7. Allaha mekan belirtmemek 8. Kuran-ı Kerime şüphesiz inanmak.' },
      { id: 's2_ilm_25', konu: 'İmanın Şartları ve Kaleleri', soru: 'İmanın koruyucu kaleleri nedir?', cevap: 'Farzlar, vacipler, sünnetler, müstehaplar, menduplar, nafileler.' },
      { id: 's2_ilm_26', konu: 'Ef\'al-i Mükellefin', soru: 'Ef\'al-i Mükellefîn nedir?', cevap: 'Mükelleflerin yapmaları veya yapmamaları gereken şeylerdir.' },
      { id: 's2_ilm_27', konu: 'Ef\'al-i Mükellefin', soru: 'Ef\'âl-i mükellefîn kaçtır? Açıklayınız.', cevap: 'Sekizdir: Farz (farz-ı ayın, farz-ı kifaye), vacip, sünnet (müekkede, gayr-ı müekkede), müstehap, mübah, mekruh, müfsid, haram.' },
      { id: 's2_ilm_28', konu: 'Ef\'al-i Mükellefin', soru: 'Farz nedir?', cevap: 'Kesin deliller ile sabit olan, Allahü Teala ve Peygamber Efendimizin emrettikleri hükümlerdir.' },
      { id: 's2_ilm_29', konu: 'Ef\'al-i Mükellefin', soru: 'Farz-ı ayın nedir?', cevap: 'Her Müslümanın ancak kendisinin yapması ile yerine gelen amellerdir. Beş vakit namaz gibi.' },
      { id: 's2_ilm_30', konu: 'Ef\'al-i Mükellefin', soru: 'Farz-ı kifaye nedir?', cevap: 'Bazı Müslümanların yapmaları ile diğer Müslümanlardan sorumluluğu kaldıran farzlardır. Cenaze namazı gibi.' },
      { id: 's2_ilm_31', konu: 'Ef\'al-i Mükellefin', soru: 'Vacip nedir?', cevap: 'Farz kadar kesin olmamakla birlikte Allâhü Teala tarafından yapılması emredilen amellerdir. Kurban kesmek ve vitir namazı gibi.' },
      { id: 's2_ilm_32', konu: 'Ef\'al-i Mükellefin', soru: 'Sünnet nedir?', cevap: 'Peygamber Efendimizin mübarek sözü, yaptıkları ve başkası yaptığında hoş gördüğü şeylerdir.' },
      { id: 's2_ilm_33', konu: 'Ef\'al-i Mükellefin', soru: 'Sünnet-i müekkede nedir?', cevap: 'Peygamber Efendimizin devamlı olarak yapıp çok az terk ettiği sünnetlerdir. Sabah ve öğle namazının sünnetleri gibi.' },
      { id: 's2_ilm_34', konu: 'Ef\'al-i Mükellefin', soru: 'Sünnet-i gayr-i müekkede nedir?', cevap: 'Peygamber Efendimizin bazen yapıp çoğu kere terk ettiği sünnetlerdir. İkindi ve yatsı namazının ilk sünnetleri gibi.' },
      { id: 's2_ilm_35', konu: 'Ef\'al-i Mükellefin', soru: 'Müstehap nedir?', cevap: 'Peygamber Efendimizin bazen işlediği şeylerdir. Sadaka vermek gibi.' },
      { id: 's2_ilm_36', konu: 'Ef\'al-i Mükellefin', soru: 'Mübah nedir?', cevap: 'Yapılmasında sevap, yapılmamasında günah olmayan şeylerdir. Oturmak, kalkmak gibi.' },
      { id: 's2_ilm_37', konu: 'Ef\'al-i Mükellefin', soru: 'Mekruh nedir?', cevap: 'İşlenmesi hoş görülmeyen ve amellerin sevabını azaltan şeylerdir. Namazdayken esnemek gibi.' },
      { id: 's2_ilm_38', konu: 'Ef\'al-i Mükellefin', soru: 'Müfsid nedir?', cevap: 'Başlanılan bir ibadeti bozan şeylerdir. Namazdayken gülmek gibi.' },
      { id: 's2_ilm_39', konu: 'Ef\'al-i Mükellefin', soru: 'Haram nedir?', cevap: 'Yapılması kesin delille yasaklanan şeylerdir. Hırsızlık yapmak gibi.' },
      { id: 's2_ilm_40', konu: 'İslam\'ın Şartları', soru: 'İslam\'ın şartları kaçtır? Nelerdir?', cevap: 'Beştir: 1. Kelime-i şehadet getirmek 2. Namaz kılmak 3. Zekat vermek 4. Ramazanı Şerif orucunu tutmak 5. Hac etmek.' },
      { id: 's2_ilm_41', konu: 'İslam\'ın Şartları', soru: 'Kelime-i Şehadet ve anlamı nedir?', cevap: 'Ben şehadet ederim ki Allah\'tan başka ilah yoktur ve ben yine şehadet ederim ki Muhammed aleyhisselam Allah\'ın kulu ve rasulüdür.' },
      { id: 's2_ilm_42', konu: 'Namaz', soru: 'Namazın farzlarını sayar mısın?', cevap: 'Namazın Farzı 12\'dir. Şartları: Hadastan Taharet, Necasetten Taharet, Setr-i Avret, İstikabeli Kıble, Vakit, Niyet. Rükünler: İftitah Tekbiri, Kıyam, Kıraat, Rüku, Secde, Ka\'de-i Ahire.' },
      { id: 's2_ilm_43', konu: 'Abdest', soru: 'Abdestin farzı nedir?', cevap: '1. Yüzü yıkamak 2. Elleri ve kolları dirseklerle birlikte yıkamak 3. Başın dörtte birini meshetmek 4. Ayakları topuklarla beraber bileklere kadar yıkamak.' },
      { id: 's2_ilm_44', konu: 'Abdest', soru: 'Abdestin sünnetleri nedir? (Beş madde sayınız.)', cevap: '1. Eûzü ve Besmele ile başlamak 2. Niyet etmek 3. Önce elleri bileklerine kadar yıkamak 4. Ağza ve burna üç kere su vermek 5. Misvak kullanmak.' },
      { id: 's2_ilm_45', konu: 'Abdest', soru: 'Abdestin mekruhları nedir? (Beş madde sayınız.)', cevap: '1. Sol el ile ağza su vermek 2. Sağ el ile sümkürmek 3. Suyu yüze çarpmak 4. Suyu israf etmek veya çok az kullanmak 5. Abdest alırken konuşmak.' },
      { id: 's2_ilm_46', konu: 'Abdest', soru: 'Abdesti bozan durumlar nedir? (Beş madde sayınız.)', cevap: '1. Küçük veya büyük tuvaletini yapmak 2. Önden veya arkadan sıvı çıkması 3. Vücuttan kan veya irin akması 4. Ağız dolusu kusmak 5. Bayılmak veya delirmek 6. Arkadan yel çıkması.' },
      { id: 's2_ilm_47', konu: 'Gusül', soru: 'Gusül abdesti nedir?', cevap: 'Ağız ve burnun içi dahil olmak üzere baştan ayağa bütün vücudu yıkayarak yapılan dini bir temizliktir.' },
      { id: 's2_ilm_48', konu: 'Gusül', soru: 'Gusül ne zaman gerekir?', cevap: 'Eşler arasındaki cinsi yakınlık, ihtilam, hayız ve nifasın bitmesiyle gerekir.' },
      { id: 's2_ilm_49', konu: 'Gusül', soru: 'Cünüp iken yapılamayacak ibadetler nelerdir?', cevap: 'Namaz kılamaz, camiye giremez, tilavet secdesi yapamaz, Kur\'an-ı Kerimi eline alamaz ve okuyamaz, Kabe\'yi tavaf edemez.' },
      { id: 's2_ilm_50', konu: 'Gusül', soru: 'Guslün farzları nedir?', cevap: '1. Ağza dolu dolu su vermek 2. Burna dolu dolu su vermek 3. Bütün bedeni kuru yer kalmayacak şekilde yıkamak.' },
      { id: 's2_ilm_51', konu: 'Gusül', soru: 'Guslün sünnetleri nedir?', cevap: '1. Niyet etmek 2. Ön ve arka avret yerlerini yıkamak 3. Besmele çekmek 4. Önce başına sonra sağ daha sonra sol omuzuna üçer defa su dökmek ve her defasında vücudu ovmak.' },
      { id: 's2_ilm_52', konu: 'Teyemmüm', soru: 'Teyemmüm nedir?', cevap: 'Su bulunmadığı veya kullanılamadığı hallerde niyet ederek elleri temiz toprağa vurup yüz ve kolları meshetmektir.' },
      { id: 's2_ilm_53', konu: 'Teyemmüm', soru: 'Teyemmümün farzı kaçtır? Sayar mısın?', cevap: 'İkidir: 1. Niyet 2. İki darp (toprağa vurmak) ve mesh (yüzü, ardından kolları meshetmek).' },
      { id: 's2_ilm_54', konu: 'Teyemmüm', soru: 'Teyemmümü bozan durumlar nelerdir?', cevap: '1. Abdesti ve guslü bozan her şey 2. Teyemmümü gerektiren durumun ortadan kalkması 3. Su bulunması veya su kullanma engelinin kalkması.' },
      { id: 's2_ilm_55', konu: 'Mestler Üzerine Mesh', soru: 'Mest üzerine mesh yapılabilmesi için ne gereklidir?', cevap: '1. Mestler abdestli iken giyilmiş olmalı 2. Mestler topuklarla birlikte ayakları örtmeli 3. Mestler bağsız olarak ayakta durabilecek şekilde kalın olmalı.' },
      { id: 's2_ilm_56', konu: 'Mestler Üzerine Mesh', soru: 'Meshin süresi nedir?', cevap: 'Abdestli olarak mest giyildikten sonra 1 gün 1 gece (24 saat); yolcu için 3 gün 3 gece (72 saat).' },
      { id: 's2_ilm_57', konu: 'Mestler Üzerine Mesh', soru: 'Mest üzerine meshin bozulduğu durumlar nelerdir?', cevap: '1. Abdesti ve guslü bozan her şey 2. Mestin ayaktan çıkması 3. Ayaklardan birinin çoğunun ıslanması 4. Mesh süresinin bitmesi.' },
      { id: 's2_ilm_58', konu: 'Necasetten Taharet', soru: 'Necaset kapsamına giren şeyler nelerdir?', cevap: 'İnsanın ön ve arkadan çıkan pisliği; eti yenmeyen hayvanların sidiği, dışkısı; tavuk, kaz, ördek dışkısı; kan, irin, meni; ağız dolusu kusuntu; haram içkiler.' },
      { id: 's2_ilm_59', konu: 'Necasetten Taharet', soru: 'İstincâ, İstinkâ ve İstibrâ nedir?', cevap: 'İstincâ: Tuvaletten sonra avret yerini temizlemek. İstinkâ: Önce kuru şeyle silip sonra suyla yıkamak. İstibrâ: Erkeklerin idrar sonrası akıntıyı kesmesi.' },
      { id: 's2_ilm_60', konu: 'Setr-i Avret', soru: 'Erkeklerin ve kadınların avret yerleri neresidir?', cevap: 'Erkekler: Göbeğin altı ile diz kapaklarının altı arasıdır. Kadınlar: Elleri, ayakları ve yüzleri hariç bütün vücutları avret mahallidir.' },
      { id: 's2_ilm_61', konu: 'Namaz Konuları', soru: 'Kerahet vakitleri nelerdir?', cevap: 'Güneş doğduktan sonra ~40-50 dk; öğle namazından önceki ~20 dk; güneş batarken akşam namazından önceki ~45 dk. Bu vakitlerde farz dışı namaz kılınmaz, tilavet secdesi yapılmaz.' },
      { id: 's2_ilm_62', konu: 'Namaz Konuları', soru: 'İftitah tekbiri, Kıyam, Kıraat, Rüku, Secde ve Ka\'de-i Ahîre\'yi kısaca açıklayınız.', cevap: 'İftitah: "Allahü Ekber" ile namaza başlamak. Kıyam: Ayakta durmak. Kıraat: Kur\'an okumak. Rüku: Baş-sırt düz eğilmek. Secde: Alın, burun, eller, dizler, ayak parmakları yere. Ka\'de-i Ahîre: Son oturuşta Ettehıyyatü okumak.' },
      { id: 's2_ilm_63', konu: 'Sehiv Secdesi', soru: 'Sehiv secdesi nedir? Gereken durumlar nelerdir?', cevap: 'Namazda unutarak yapılan eksiklik veya fazlalığı düzeltmek için yapılan vacip secdedir. Vacibi terk etme, farzı geciktirme, birinci oturuşu unutma gibi durumlarda gerekir.' },
    ],

    'Tecvid': [
      { id: 's2_tec_1', konu: 'İdgam', soru: 'İdgam-ı Bila Gunne nedir ve harfleri nelerdir?', cevap: 'Tenvin ve nuni sakinden sonra lam veya ra harfi gelirse idgam-ı bila gunne olur. Harfleri: ل - ر' },
      { id: 's2_tec_2', konu: 'İdgam', soru: 'İdgam-ı Misleyn neye derler ve tarifi nedir?', cevap: 'Sakin olan bir harf kendi misline (aynı harfe) uğrarsa idgam-ı misleyn olur.' },
      { id: 's2_tec_3', konu: 'İdgam', soru: 'Nunu sakin nuna uğrasa ne tecvid olur?', cevap: 'Hem idgam-ı misleyn hem de idgam-ı meal gunne olur.' },
      { id: 's2_tec_4', konu: 'İdgam', soru: 'Mimi sakinin kaç hali vardır, nelerdir?', cevap: '3 hali vardır: 1. İdgam-ı misleyn meal gunne (mime uğrarsa) 2. İhfa-i Şefevi (be\'ye uğrarsa) 3. İzhar-ı Şefevi (mim ve be haricindeki 26 harfe uğrarsa).' },
      { id: 's2_tec_5', konu: 'İdgam', soru: 'İdgam-ı Mütecaniseyn neye derler ve harfleri kaç mahreçtedir?', cevap: 'Mahreçleri bir, sıfatları başka olan harfler birbirine uğrarsa olur. 3 Mahreç: (Ta-Dal-Te), (Za-Zel-Se), (Be-Mim).' },
      { id: 's2_tec_6', konu: 'İdgam', soru: 'İdgam-ı Mütegaribeynin tarifi nedir ve harfleri kaç mahreçtedir?', cevap: 'Mahrecinde ve sıfatında yakınlığı olan harfler birbirine uğrarsa olur. 2 Mahreç: (Lam-Ra), (Kaf-Kef).' },
      { id: 's2_tec_7', konu: 'Lam Harfi', soru: 'İdgam-ı Şemsiyye neye denir ve harfleri nelerdir?', cevap: 'Lamı tariften sonra idgam-ı şemsiyye harflerinden biri gelirse olur. 14 harf vardır.' },
      { id: 's2_tec_8', konu: 'Lam Harfi', soru: 'İzhar-ı Kameriyye neye denir ve harfleri nelerdir?', cevap: 'Lamı tariften sonra izhar-ı kameriyye harfleri gelirse olur. 14 harf vardır.' },
      { id: 's2_tec_9', konu: 'Kalkale', soru: 'Kalkalenin tarifi nedir ve harfleri nelerdir?', cevap: 'Kuvvetli bir ses işitilinceye kadar harfin mahrecini sarsmaktır. Harfleri: ق ط ب ج د (kutbu ced).' },
      { id: 's2_tec_10', konu: 'Çeşitli Konular', soru: 'Hurufu istila (Hükmürra) harfleri nelerdir?', cevap: 'خُصَّ ضَغْطٍ قِظ harfleridir.' },
      { id: 's2_tec_11', konu: 'Çeşitli Konular', soru: 'Lafzatullah ne zaman kalın ve ince okunur?', cevap: 'Ma gabli meftuh veya mezmum olursa kalın, meksür olursa ince okunur.' },
      { id: 's2_tec_12', konu: 'Çeşitli Konular', soru: 'Zamir bahsini anlatınız.', cevap: 'Zamirin ma gabli müteharrik (harekeli) olursa med ile uzatılır. Ma gabli sakin olursa med olunmaz, kasr olunur.' },
      { id: 's2_tec_13', konu: 'Çeşitli Konular', soru: 'Sektenin tarifi nedir ve Kur\'an-ı Kerim\'de kaç yerdedir?', cevap: 'Nefes vermeksizin sesi kesmektir. 4 yerdedir: Mutaffifin, Kıyame, Yasin, Kehf.' },
    ],
  },
};
